name: "Pironman 5 alpha"
description: "Pironman 5 support alpha"
version: "0.0.9"
slug: "pironman5"
init: false
arch:
  - aarch64
  - armhf
startup: application
devices:
  - /dev/i2c-1
  - /dev/spidev0.0
  - /dev/mem
gpio: true
hassio_api: true
hassio_role: "manager"
map:
 - addon_config:rw

webui: "http://[HOST]:[PORT:34001]"
ports: 
  34001/tcp: 34001
ports_description:
  34001/tcp: Pironman 5 Dashboard
panel_icon: mdi:view-dashboard
ingress: true
ingress_port: 34001