build_from:
  # aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:8.2.1
  aarch64: ghcr.io/hassio-addons/ubuntu-base/armv7:latest
  armhf: ghcr.io/hassio-addons/ubuntu-base/armv7:latest
  # aarch64: ghcr.io/home-assistant/armhf-base-raspbian:bullseye
  # armhf: ghcr.io/home-assistant/armhf-base-raspbian:bullseye
