name: "Pironman"
description: "Pironman support"
version: "1.0.9"
slug: "pironman"
init: false
arch:
  - aarch64
  - armhf
startup: application
devices:
  - /dev/i2c-1
  - /dev/spidev0.0
  - /dev/mem
gpio: true
devicetree: true
host_network: true
full_access: true
privileged:
  - SYS_RAWIO
  - SYS_RESOURCE
hassio_api: true
hassio_role: "manager"
journald: true
options:
  temperature_unit: "C"
  fan_temp: 50
  display_always_on: false
  display_on_for: 30
  rgb_on: true
  rgb_style: "breath"
  rgb_color: "0a1aff"
  rgb_speed: 50
  rgb_freq: 1000
  rgb_pin: "10"
schema:
  temperature_unit: "list(C|F)"
  fan_temp: int # (30, 80)
  display_always_on: bool
  display_on_for: int
  rgb_on: bool
  rgb_style: "list(breath|leap|flow|raise_up|colorful)"
  rgb_color: str
  rgb_speed: int # (0, 100)
  rgb_freq: int # (400, 1600)
  rgb_pin: "list(10|12|21)"
